export const ACCOUNT_STATUSES = {
  REGISTRATION_INITIATED: "REGISTRATION_INITIATED",
  EMAIL_VERIFICATION_PENDING: "EMAIL_VERIFICATION_PENDING",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  ADMIN_APPROVAL_PENDING: "ADMIN_APPROVAL_PENDING",
  ACCOUNT_PARTIALLY_APPROVED: "ACCOUNT_PARTIALLY_APPROVED",
  DOCUMENTS_UPLOAD_PENDING: "DOCUMENTS_UPLOAD_PENDING",
  DOCUMENTS_REVIEW_PENDING: "DOCUMENTS_REVIEW_PENDING",
  DOCUMENTS_APPROVED: "DOCUMENTS_APPROVED",
  DOCUMENTS_REJECTED: "DOCUMENTS_REJECTED",
  ACCOUNT_APPROVED: "ACCOUNT_APPROVED",
  ACCOUNT_REJECTED: "ACCOUNT_REJECTED",
};

export const LABELS = {
  [ACCOUNT_STATUSES.REGISTRATION_INITIATED]: "Registeration Initiated",
  [ACCOUNT_STATUSES.EMAIL_VERIFICATION_PENDING]: "Email Verification Pending",
  [ACCOUNT_STATUSES.EMAIL_VERIFIED]: "Email Verified",
  [ACCOUNT_STATUSES.ADMIN_APPROVAL_PENDING]: "Admin Approval Pending",
  [ACCOUNT_STATUSES.ACCOUNT_PARTIALLY_APPROVED]: "Partially Approved",
  [ACCOUNT_STATUSES.DOCUMENTS_UPLOAD_PENDING]: "Documents Upload Pending",
  [ACCOUNT_STATUSES.DOCUMENTS_REVIEW_PENDING]: "Documents Review Pending",
  [ACCOUNT_STATUSES.DOCUMENTS_APPROVED]: "Documents Approved",
  [ACCOUNT_STATUSES.DOCUMENTS_REJECTED]: "Documents Rejected",
  [ACCOUNT_STATUSES.ACCOUNT_APPROVED]: "Approved",
  [ACCOUNT_STATUSES.ACCOUNT_REJECTED]: "Rejected",
};

export const COLORS = {
  [ACCOUNT_STATUSES.REGISTRATION_INITIATED]: "#bebebe",
  [ACCOUNT_STATUSES.EMAIL_VERIFICATION_PENDING]: "#00aced",
  [ACCOUNT_STATUSES.EMAIL_VERIFIED]: "#90ee90",
  [ACCOUNT_STATUSES.ADMIN_APPROVAL_PENDING]: "#00aced",
  [ACCOUNT_STATUSES.ACCOUNT_PARTIALLY_APPROVED]: "#90ee90",
  [ACCOUNT_STATUSES.DOCUMENTS_UPLOAD_PENDING]: "#808080",
  [ACCOUNT_STATUSES.DOCUMENTS_REVIEW_PENDING]: "#949494",
  [ACCOUNT_STATUSES.DOCUMENTS_APPROVED]: "#90ee90",
  [ACCOUNT_STATUSES.DOCUMENTS_REJECTED]: "#F29339",
  [ACCOUNT_STATUSES.ACCOUNT_APPROVED]: "#5cb85c",
  [ACCOUNT_STATUSES.ACCOUNT_REJECTED]: "#D9512C",
};
