export const MOVE_STATUS = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  SCHEDULED: "SCHEDULED",
  ONGOING: "ONGOING",
  STARTED: "STARTED",
  DONE: "DONE",
};

export const LABELS = {
  [MOVE_STATUS.DRAFT]: "DRAFT",
  [MOVE_STATUS.PENDING]: "PENDING",
  [MOVE_STATUS.SCHEDULED]: "SCHEDULED",
  [MOVE_STATUS.ONGOING]: "ONGOING",
  [MOVE_STATUS.STARTED]: "STARTED",
  [MOVE_STATUS.DONE]: "DONE",
};

export const COLORS = {
  [MOVE_STATUS.DRAFT]: "#CCCCCC",
  [MOVE_STATUS.PENDING]: "#37474f",
  [MOVE_STATUS.SCHEDULED]: "#FFA500",
  [MOVE_STATUS.ONGOING]: "#4169E1",
  [MOVE_STATUS.STARTED]: "#FFA500",
  [MOVE_STATUS.DONE]: "#006400",
};
