[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "cp .env.example .env || echo 'APP_KEY=' > .env",
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
    "mkdir -p bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache",
    "php artisan key:generate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PORT = "8000"
