[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = { name = "APP_KEY" }
LOG_CHANNEL = "stderr"
LOG_STDERR_FORMATTER = "json"
SESSION_DRIVER = "cookie"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/tmp/database.sqlite"
