[build]
builder = "nixpacks"
buildCommand = "npm run build"  # or "yarn build" if you're using Yarn

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"  # "never" disables auto-restarts; "on-failure" is safer

[env]
APP_ENV = "production"
APP_DEBUG = "false"