[build]
builder = "nixpacks"
buildCommand = "npm run build"  # or "yarn build" if you're using Yarn

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
APP_ENV = "production"
APP_DEBUG = "false"
