[build]
builder = "railpack"
railpackVersion = "0.2.4"

[build.railpack]
packageManager = "npm"
installCommand = "npm install"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm start"

[env]
NODE_ENV = "production"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
