name: Deploy Laravel App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, zip, fileinfo, openssl, tokenizer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: movers_back/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('movers_back/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist || cat composer.lock
        working-directory: movers_back

      - name: Check vendor folder
        run: ls -la
        working-directory: movers_back

      - name: Copy .env file
        run: cp .env.example .env
        working-directory: movers_back

      - name: Generate app key
        run: php artisan key:generate
        working-directory: movers_back

      - name: Set correct permissions
        run: chmod -R 775 storage bootstrap/cache
        working-directory: movers_back

      - name: Cache config
        run: php artisan config:cache
        working-directory: movers_back

      - name: Cache routes
        run: php artisan route:cache
        working-directory: movers_back

      - name: Cache views
        run: php artisan view:cache
        working-directory: movers_back
